name: studyriver-en-feeds

on:
  schedule:
    # JST 月曜08:00  →  UTC 日曜23:00
    - cron: "0 23 * * 0"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: "3.12" }

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Generate newsletter markdown
        run: python scripts/generate_newsletter.py

      # ↓ 生成物をコミット & プッシュ
      - name: Commit changes
        run: |
          git config --local user.name  "actions-bot"
          git config --local user.email "actions@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add 05.NewsLetter/en/*.md
            git commit -m "chore(newsletter): weekly feeds ($(date -u '+%Y-%m-%d'))"
            git push
          else
            echo "No changes"
          fi
        env:
          # デフォルトの `GITHUB_TOKEN` で OK（リポジトリに書込権限必須）
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
